- hosts: kube-master
  gather_facts: false
  tasks:
    - name: Download helm
      get_url:
        url: https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
        dest: /tmp/helm.tgz
    - name: Descompactanto helm
      unarchive:
        src: /tmp/helm.tgz
        dest: /tmp/
        remote_src: yes
    - name: Copiando binario helm
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/bin
        remote_src: yes
        mode: 0755
    - name: Adicionando repositorio haproxy no helm
      kubernetes.core.helm_repository:
        repo_name: haproxy-ingress
        repo_url: https://haproxy-ingress.github.io/charts
        repo_state: present
    - name: Atualizando repositorio helm
      shell: /usr/bin/helm repo update
    - name: Instalando haprox ingress
      shell: |
        /usr/bin/helm install --create-namespace --namespace=haproxy-ingress ingress haproxy-ingress/haproxy-ingress \
        --set controller.kind=DaemonSet \
        --set controller.hostNetwork=True \
        --version '0.12'
