- hosts: kube-master
  gather_facts: false
  tasks:
    - name: Download helm
      get_url:
        url: https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
        dest: /tmp/helm.tgz
    - name: Descompactanto helm
      - unarchive:
        src: /tmp/helm.tgz
        dest: /tmp/
        remote_src: yes
