- hosts: kube-master
  gather_facts: false
  tasks:
    - name: Download helm
      get_url:
        url: https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
        dest: /tmp/helm.tgz
    - name: Instalando helm
      ansible.builtin.unarchive:
        src: /tmp/helm.tgz
        files: linux-amd64/helm
        dest: /usr/bin/helm
        mode: 0755
